// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR51t2JUZCO_xhy2hxWtCpKZARFWrNnDI',
    appId: '1:694721152780:web:517575c5c2ae1488f36b29',
    messagingSenderId: '694721152780',
    projectId: 'tomatelo',
    authDomain: 'tomatelo.firebaseapp.com',
    storageBucket: 'tomatelo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL_2bJHhpDTDfnsWJui6O7sIf6uQ9ht8E',
    appId: '1:694721152780:android:6c16463a495c4943f36b29',
    messagingSenderId: '694721152780',
    projectId: 'tomatelo',
    storageBucket: 'tomatelo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAELio-U_GDBWzC_Ml8ApIc4zYHBQFvaMY',
    appId: '1:694721152780:ios:c42ce984777b9a6bf36b29',
    messagingSenderId: '694721152780',
    projectId: 'tomatelo',
    storageBucket: 'tomatelo.firebasestorage.app',
    iosBundleId: 'com.example.tomatelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAELio-U_GDBWzC_Ml8ApIc4zYHBQFvaMY',
    appId: '1:694721152780:ios:c42ce984777b9a6bf36b29',
    messagingSenderId: '694721152780',
    projectId: 'tomatelo',
    storageBucket: 'tomatelo.firebasestorage.app',
    iosBundleId: 'com.example.tomatelo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR51t2JUZCO_xhy2hxWtCpKZARFWrNnDI',
    appId: '1:694721152780:web:bc63ef4e86851350f36b29',
    messagingSenderId: '694721152780',
    projectId: 'tomatelo',
    authDomain: 'tomatelo.firebaseapp.com',
    storageBucket: 'tomatelo.firebasestorage.app',
  );
}
